# Generated by Django 5.1.1 on 2024-11-07 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id_clinica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clinica', models.CharField(max_length=100)),
                ('correo_clinica', models.EmailField(max_length=100)),
                ('telefono_clinica', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('rut_doctor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres_doctor', models.CharField(max_length=100)),
                ('primer_apellido_doctor', models.CharField(max_length=50)),
                ('segundo_apellido_doctor', models.CharField(blank=True, max_length=50)),
                ('correo_doctor', models.EmailField(max_length=100)),
                ('telefono_doctor', models.CharField(max_length=15)),
                ('fecha_nacimiento_doctor', models.DateField(blank=True, null=True)),
                ('especialidad_doctor', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut_paciente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres_paciente', models.CharField(max_length=100)),
                ('primer_apellido_paciente', models.CharField(max_length=50)),
                ('segundo_apellido_paciente', models.CharField(blank=True, max_length=50)),
                ('correo_paciente', models.EmailField(max_length=100)),
                ('telefono_paciente', models.CharField(max_length=15)),
                ('fecha_nacimiento_paciente', models.DateField(blank=True, null=True)),
                ('direccion_paciente', models.CharField(blank=True, max_length=100)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_pacientes/')),
                ('genero_paciente', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No binario')], max_length=2)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_informe', models.CharField(max_length=200)),
                ('descripcion_informe', models.TextField(default='Descripción por defecto.')),
                ('notas_doctor', models.TextField(blank=True)),
                ('instrucciones_tratamiento', models.TextField(blank=True)),
                ('fecha_informe', models.DateTimeField(auto_now_add=True)),
                ('documentos_extra', models.FileField(blank=True, upload_to='documentos_extra/')),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultorioCys.clinica')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.paciente')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('motivo_consulta', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteInforme',
            fields=[
                ('id_paciente_informe', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.informe')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.paciente')),
            ],
            options={
                'verbose_name': 'Paciente Informe',
                'verbose_name_plural': 'Informes de Pacientes',
            },
        ),
        migrations.CreateModel(
            name='SedeClinica',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('region_sede', models.CharField(max_length=30)),
                ('comuna_sede', models.CharField(max_length=30)),
                ('direccion_sede', models.CharField(max_length=100)),
                ('telefono_sede', models.CharField(max_length=15)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.clinica')),
            ],
            options={
                'verbose_name': 'Sede Clínica',
                'verbose_name_plural': 'Sedes Clínicas',
            },
        ),
        migrations.AddField(
            model_name='informe',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultorioCys.sedeclinica'),
        ),
        migrations.CreateModel(
            name='DoctorClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.doctor')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.sedeclinica')),
            ],
            options={
                'verbose_name': 'Doctor en Sede',
                'verbose_name_plural': 'Doctores en Sedes',
                'unique_together': {('doctor', 'sede')},
            },
        ),
    ]
