# Generated by Django 5.1.1 on 2024-11-10 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioCys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorioCys.doctor')),
            ],
            options={
                'verbose_name': 'Disponibilidad del Doctor',
                'verbose_name_plural': 'Disponibilidades de Doctores',
                'unique_together': {('doctor', 'fecha', 'hora')},
            },
        ),
    ]
