# Generated by Django 5.1.1 on 2024-11-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorioCys', '0002_disponibilidaddoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
